<section id="pageAdmin">
    <h2>Administration/Gestion des partenaires</h2>
    <!--liens de navigation-->
    <nav>
        <ul>
            <li><a href="index.php?controller=News&action=list"> Gestion des news</a></li>
            <li><a href="index.php?controller=Category">Gestion des catégories</a></li>
            <li><a href="index.php?controller=Sponsors"> Gestion des sponsors</a></li>
            <li><a href="index.php?controller=Teams&action=list">Gestion des équipes</a></li>
            <li><a href="index.php?controller=Season">Gestion des saisons</a></li>
            <li><a href="index.php?controller=Level">Gestion des niveaux</a></li>
            <li><a href="index.php?controller=Player&action=list">Gestion des joueurs</a></li>
            <li><a href="index.php?controller=Position">Gestion des postes</a></li>
            <li><a href="index.php?controller=Contact&action=list">Gestion des contacts</a></li>
            <li><a href="index.php?controller=Becomeeducator&action=list">Gestion des educateurs</a></li>
            <li><a href="index.php?controller=User">Gestion des utilisateurs</a></li>
        </ul>
    </nav>
    <table>
        <caption>Gestion des Partenaires</caption>
        <tr>
            <th>Nom</th>
            <th>Email</th>
            <th>Message</th>
            <th>Voir détails</th>
            <th>Supprimer</th>
        </tr>
        <?php foreach ($partners as $partner) : ?>
            <tr>
                <td><?= $partner->getNom() ?></td>
                <td><?= $partner->getEmail() ?></td>
                <td><?= substr($partner->getMessage(), 0, 20) ?>...</td>
                <td><a href="?controller=Becomepartner&action=lookDetails&id=<?= $partner->getId() ?>">Voir détails</a></td>
                <td><a class="suppr" href="index.php?controller=Becomepartner&action=delete&id=<?= $partner->getId() ?>">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p>Liste des partenaires classés par ordre chronologique inversé :(<em><?= count($partners) ?></em> partenaires au total)</p>
</section>