<section id="pageAdmin">
    <h2>Administration/Gestion des sponsors</h2>
    <a class="bouton" href="index.php?controller=Sponsors&action=insert">Créer un sponsor</a>
    <!--liens de navigation-->
    <nav>
        <ul>
            <li><a href="index.php?controller=Category"> Gestion des catégories</a></li>
            <li><a href="index.php?controller=News&action=list"> Gestion des news</a></li>
            <li><a href="index.php?controller=Teams&action=list">Gestion des équipes</a></li>
            <li><a href="index.php?controller=Season">Gestion des saisons</a></li>
            <li><a href="index.php?controller=Level">Gestion des niveaux</a></li>
            <li><a href="index.php?controller=Player&action=list">Gestion des joueurs</a></li>
            <li><a href="index.php?controller=Position">Gestion des postes</a></li>
            <li><a href="index.php?controller=Contact&action=list">Gestion des contacts</a></li>
            <li><a href="index.php?controller=Becomepartner&action=list">Gestion des partenaires</a></li>
            <li><a href="index.php?controller=Becomeeducator&action=list">Gestion des educateurs</a></li>
            <li><a href="index.php?controller=User">Gestion des utilisateurs</a></li>
        </ul>
    </nav>
    <!--tableau qui affiche la liste-->
    <table>
        <caption>Gestion des sponsors</caption>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        <?php foreach ($sponsors as $sponsor) : ?>
            <tr>
                <td><?= $sponsor->getId() ?></td>
                <td><?= $sponsor->getTitle() ?></td>
                <td><a class="modif" href="index.php?controller=Sponsors&action=edit&id=<?= $sponsor->getId() ?>">Modifier</a></td>
                <td><a class="suppr" href="index.php?controller=Sponsors&action=delete&id=<?= $sponsor->getId() ?>">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p>Liste des sponsors :(<em><?= count($sponsors) ?></em> sponsors au total)</p>
</section>