<section id="pageAdmin">
    <h2>Administration/Gestion des utilisateurs</h2>
    <a class="bouton" href="index.php?controller=User&action=insert">Créer un utilisateur</a>
     <!--liens de navigation-->
    <nav>
        <ul>
            <li><a href="index.php?controller=News&action=list"> Gestion des news</a></li>
            <li><a href="index.php?controller=Category">Gestion des catégories</a></li>
            <li><a href="index.php?controller=Sponsors"> Gestion des sponsors</a></li>
            <li><a href="index.php?controller=Teams&action=list">Gestion des équipes</a></li>
            <li><a href="index.php?controller=Season">Gestion des saisons</a></li>
            <li><a href="index.php?controller=Level">Gestion des niveaux</a></li>
            <li><a href="index.php?controller=Player&action=list">Gestion des joueurs</a></li>
            <li><a href="index.php?controller=Position">Gestion des postes</a></li>
            <li><a href="index.php?controller=Contact&action=list">Gestion des contacts</a></li>
            <li><a href="index.php?controller=Becomepartner&action=list">Gestion des partenaires</a></li>
            <li><a href="index.php?controller=Becomeeducator&action=list">Gestion des educateurs</a></li>
        </ul>
    </nav>
    <!--tableau qui affiche la liste-->
    <table>
        <caption>Gestion des Utilisateurs</caption>
        <tr>
            <th>ID</th>
            <th>Utilisateur</th>
            <th>Email</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?= $user->getUserId() ?></td>
                <td><?= $user->getUserName() ?></td>
                <td><?= $user->getEmail() ?></td>
                <td><a class="modif" href="index.php?controller=User&action=edit&id=<?= $user->getUserId() ?>">Modifier</a></td>
                <td><a class="suppr" href="index.php?controller=User&action=delete&id=<?= $user->getUserId() ?>">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p>Liste des utilisateurs : (<em><?= count($users) ?></em> utilisateurs au total)</p>
</section>