<section id="pageContact">
    <article class="desc contact">
        <h3>Devenez un partenaire ou un sponsor de l'ASFAC...</h3>
        <img src="img/asfac-contact.jpg" alt="ASFAC_Contact">
        <p>Vous souhaitez apporter un soutien au club, en tant que partenaire, sponsor ou autres, vous souhaitez associer l'image de votre société avec celle de l'ASFAC, faire apparaitre votre entreprise sur nos maillots , sur les panneaux publicitaires du stade, notre site Internet ou autres.</p>
        <p>L'Asfac se tient à votre disposition pour toutes vos demandes.</p>
        <p>N'hesitez pas a contacter notre equipe au 04.67.80.07.44</p>
        <img src="img/contact-mail-asfac.jpg" alt="ASFAC_Email">
        <p>Email : athletic-club@wanadoo.fr</p>
    </article>
    <!--formulaire de contact en tant que partenaire-->
    <form method="post" action="index.php?controller=Becomepartner&action=insert" id="formRegistration2">
        <fieldset>
            <legend>Contactez nous</legend>
            <ul>
                <li>
                    <label for="lastName">Nom* :</label>
                    <input id="lastName" type="text" name="lastName" required>
                </li>
                <li>
                    <label for="firstName">Prénom :</label>
                    <input id="firstName" type="text" name="firstName">
                </li>
                <li>
                    <label class="textarea" for="address">Adresse :</label>
                    <textarea id="address" name="address" rows="3"></textarea>
                </li>
                <li>
                    <label for="phone">Téléphone :</label>
                    <input id="phone" type="text" name="phone" class="phone">
                </li>
                <li>
                    <label for="email">E-mail* :</label>
                    <input id="email" type="email" name="email" required>
                </li>
                <li>
                    <label class="textarea" for="message">Message* :</label>
                    <textarea id="message" name="message" rows="5" required></textarea>
                </li>
            </ul>
        </fieldset>
        <p>Les champs marqués * sont obligatoires</p>
        <button type="submit">Envoyer</button>
    </form>
</section>