<section id="page">
    <h2>Educateurs</h2>
    <article class="desc">
        <h3>Etre et devenir éducateur...</h3>
        <p>Le sport est porteur de hautes valeurs morales qui en font un moyen d'éducation exceptionnel et un facteur irremplaçable d'épanouissement de la personne, d'intégration sociale et de promotion de l'homme. L'esprit sportif, c'est aussi le respect des valeurs humaines qui doivent prévaloir en tout état de cause sur les enjeux de la compétition, enjeux économiques compris.</p>
        <h3>JEUNE CADRE TECHNIQUE</h3>
        <p>Ce stage s’adresse au jeune mineur de 16 – 17 ans s’occupant d’une école de Foot (Débutants – Poussins - Benjamins) ou Aide éducateur de l’Ecole de Football de son club.</p>
        <p>C’est le Club qui doit faire la demande d’inscription, auprès de son district, pour son futur éducateur.</p>
        <p>Programme :</p>
        <ul>
            <li>Animation de plateaux</li>
            <li>Arbitrage du Foot à 5 à 7 à 9.</li>
            <li>Séance d’Entraînement pour le foot de masse.</li>
        </ul>
        <h3>INITIATEUR DE FOOTBALL 1er NIVEAU FORMATION MODULAIRE</h3>
        <p>Les personnes majeures souhaitant obtenir l’Initiateur 1er niveau devront passer les 3 modules sur une période de 2 ans.</p>
        <p>Les modules se décomposent comme suit :</p>
        <ul>
            <li>Module Débutants 12 heures Basé sur le l’éveil et le jeu festif</li>
            <li>Module Poussins 12 heures Basé sur l’Initiation par le jeu</li>
            <li>Module Benjamins 18 heures Basé sur l’Initiation et apprentissage par le jeu</li>
        </ul>
        <h3>INITIATEUR DE FOOTBALL 2ème NIVEAU</h3>
        <p>Pour les éducateurs ayant le obtenue le diplôme d'Initiateur 1er Niveau, et qui désirent entraîner les jeunes de 12 à 17 ans.</p>
        <p>Basé sur :</p>
        <ul>
            <li>Pré-Formation</li>
            <li>Perfectionnement Technique du Football à 11</li>
            <li>Tactique Collective</li>
        </ul>
        <h3>ANIMATEUR SENIORS</h3>
        <p>Pour les responsables techniques des équipes seniors de district</p>
        <p>Programme:</p>
        <ul>
            <li>les Bases de l’Entraînement Senior</li>
        </ul>
        <p>Les Diplômes Fédéraux Initiateur 1- 2 et l’Animateur Seniors sont obligatoire pour passer les Brevets d’Etat</p>
        <h3>BREVET D’ETAT</h3>
        <p>Est un brevet officiel dont le programme d’enseignement et l’examen sont fixés et contrôlés par l’Etat.
            Chaque degré comprend deux parties : une partie commune à tous les sports et une partie spécifique Football</p>
        <p>Le Brevet d’Etat Educateur 1er Degré :</p>
        <ul>
            <li>Permet d’entraîner des équipes évoluant en dessous de la division d’honneur.</li>
            <li>Basé sur l’entraînement des joueurs de Ligue.</li>
        </ul>
        <p>Après un test d’entrée pour la formation :</p>
        <p>Formation en contrôle continu, spécifique et tronc commun, de 270 h en 7 fois 1 semaine.</p>
        <p>Stage de 430 h en contrôle continu.</p>
        <p>Diplôme délivré par la DDJS.</p>
        <p>Pour tous renseignements complémentaires et d’inscription prendre contact avec votre Ligue Régionale de Football.</p>
        <h3>Les Diplômes Fédéraux Adaptés</h3>
        <p>Le Diplôme d’Entraîneur de Football D.E.F.</p>
        <p>Profil :</p>
        <ul>
            <li>Entraîneur de joueurs et équipes amateurs toutes catégories.</li>
            <li>2 ans après le BE1 et avoir eu la note de 12 au spécifique et en pédagogie</li>
        </ul>
        <p>Pour tous renseignements complémentaires et d’inscription prendre contact avec le C.T.N.F.S.</p>
        <p>Si la note de 12 au D.E.F. a été obtenue au spécifique et en pédagogie le stagiaire a la possibilité de présenter</p>
        <p>le Certificat de Formateur</p>
        <p>Profil :</p>
        <ul>
            <li>Entraîneur formateur préparant des adolescents aux métiers de Footballeur Professionnel.</li>
        </ul>
        <p>Le Diplôme d’Entraîneur Professionnel de Football D.E.P.F.</p>
        <p>Profil :</p>
        <ul>
            <li>Entraînement des clubs Professionnels.</li>
            <li>Avoir eu la note de 14 au DEF</li>
        </ul>
        <p><strong>Pour tous renseignements complémentaires et d’inscription prendre contact avec le C.T.N.F.S.</strong></p>
    </article>
</section>