<?php
if (session_status() != PHP_SESSION_ACTIVE) {
    session_start();
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script|Playfair+Display">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <title>Site Officiel de l'ASFAC</title>
</head>

<body>
    <header>
        <!--logo avec lien inclus qui redirige vers la page d'acceuil-->
        <a href="index.php" class="logo"><img class="logoa" src="img/logo_asfac1.svg" alt="logo de l'asfac"></a>
        <!--liens de navigation-->
        <nav class="transparent">
            <div class="conteneur-nav">
                <label for="mobile"><i class="fas fa-bars"></i></label>
                <input type="checkbox" id="mobile" role="button">
                <ul class="navbar">
                    <li class="deroulant">
                        <p>Saison</p>
                        <ul class="sous">
                            <li><a href="index.php?controller=News">News</a></li>
                        </ul>
                    </li>
                    <li class="deroulant">
                        <p>Le Club</p>
                        <ul class="sous">
                            <li><a href="index.php?controller=Stadium">Le Stade</a></li>
                            <li><a href="index.php?controller=Staff">Le Staff</a></li>
                            <li><a href="index.php?controller=Contact">Contactez nous</a></li>
                        </ul>
                    </li>
                    <li class="deroulant">
                        <p>Equipes</p>
                        <ul class="sous">
                            <li><a href="index.php?controller=Teams">Catégories</a></li>
                        </ul>
                    </li>
                    <li class="deroulant">
                        <p>Jeunes</p>
                        <ul class="sous">
                            <li><a href="index.php?controller=Licenses">Licences</a></li>
                            <li><a href="index.php?controller=Training">Entrainements</a></li>
                            <li><a href="index.php?controller=Educator">Educateurs</a></li>
                            <li><a href="index.php?controller=Becomeeducator">Devenez Educateur</a></li>
                        </ul>
                    </li>
                    <li class="deroulant">
                        <p>Partenaires</p>
                        <ul class="sous">
                            <li><a href="index.php?controller=Partner">Nos Partenaires</a></li>
                            <li><a href="index.php?controller=Sponsors&action=show">Nos Sponsors</a></li>
                            <li><a href="index.php?controller=Becomepartner">Devenez Partenaires</a></li>
                            <li><a href="index.php?controller=Link">Liens</a></li>
                        </ul>
                    </li>
                    <li class="deroulant">
                        <p>Connexion</p>
                        <ul class="sous">
                            <!--si non connecté-->
                            <?php if (!isset($_SESSION['logged']) || $_SESSION['logged'] != true) : ?>
                                <li><a href="index.php?controller=Access">Connexion</a></li>
                                <!--si connecté-->
                            <?php else : ?>
                                <li><a href="index.php?controller=Access&action=logout">Deconnexion</a></li>
                                <li><a href="index.php?controller=News&action=list">Administration</a></li>
                            <?php endif ?>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <!--affichage de la page concernée-->
        <?php include_once $template ?>
    </main>
    <!--lien vers ligue des petits princes-->
    <section class="princes">
        <h2 id="a">La ligue des petits princes</h2>
        <a href="https://www.laliguedespetitsprinces.fr/"><img src="img/liguePetitsPrinces.png" alt="logo_ligue_des_petits_princes"></a>
    </section>
    <aside>
        <!--liens vers sponsors importants-->
        <section class="officiels">
            <h2><i class="fas fa-handshake"></i> Nos sponsors</h2>
            <div class="liens">
                <a href="https://www.credit-agricole.fr/"><img src="uploads/officiels/credit_agricole.png" alt="logo credit agricole"></a>
                <a href="http://www.ville-frontignan.fr/"><img src="uploads/officiels/ville.png" alt="logo ville frontignan"></a>
                <a href="https://www.intersport.fr/"><img src="uploads/officiels/intersport.png" alt="logo intersport"></a>
                <a href="http://www.herault.fr/"><img src="uploads/officiels/dpt-herault.png" alt="logo dpt herault"></a>
                <a href="http://www.groupenicollin.com/"><img src="uploads/officiels/Nicollin.png" alt="logo groupe nicollin"></a>
                <a href="http://www.vortex-mobilite.fr/"><img src="uploads/officiels/vortex.png" alt="logo vortex"></a>
            </div>
        </section>
        <!--liens vers réseaux sociaux-->
        <section class="reseau">
            <h2>Nos réseaux sociaux</h2>
            <div class="liens">
                <a href="https://fr-fr.facebook.com/fierdetreventrebleu"><i class="fab fa-facebook"></i></a>
                <a href="https://twitter.com/avs_frontignan"><i class="fab fa-twitter"></i></a>
                <a href="https://instagram.com/frontignan_asfac"><i class="fab fa-instagram"></i></a>
            </div>
        </section>
    </aside>
    <script src="js/script.js"></script>
    <script src="js/verif.js"></script>
</body>
<footer>
    <h2># FIER D'ETRE VENTRE BLEU</h2>
    <h3>ASFAC - avenir sportif frontignan athletic club</h3>
    <p>34110 FRONTIGNAN</p>
    <p>Ce site web à été réalisé par <a href="mailto:eddy.tranvan@sfr.fr">Eddy Tran-van</a></p>
</footer>

</html>