<section id="page">
    <h2>Licences</h2>
    <article class="desc">
        <h3>Les modalités d'inscription</h3>
        <p>Si vous souhaitez adhérer à notre club, l’équipe du site vous précise la démarche que vous devez effectuer selon le cas dans lequel vous ou votre enfant se trouve :</p>
        <img src="img/licences-asfac.jpg" alt="licences">
        <h3>Cotisations saisons 2020-2021 :</h3>
        <ul>
            <li>Vétérans (160€)</li>
            <li>Seniors 1 et 2 (300€)</li>
            <li>Féminines(260€)</li>
            <li>U14 à U20 (265€)</li>
            <li>U6 à U13 (225€)</li>
            <li>U5 (195€)</li>
            <li>Dirigeants(70€)</li>
            <li>Educateurs(95€)</li>
        </ul>
        <h3>Renouvellement :</h3>
        <p>Le cas le plus courant est le renouvellement de votre licence, cela concerne les joueurs licenciés à l’ASFAC lors de la saison précédente.</p>
        <p>Si vous ou votre enfant êtes dans cette situation il vous suffit de vous présenter au secrétariat du club muni d’une photo d’identité.</p>
        <p>L’équipe administrative vous fera alors signer votre licence que vous devrez ensuite amener à votre médecin afin qu’il la signe, la date et y appose son cachet.</p>
        <p>Il ne vous restera plus qu’à retourner la licence au secrétariat et régler votre cotisation.</p>
        <p>Cette démarche concerne toute les catégories, équipes de jeunes et séniors comprises.</p>
        <h3>Changement de club :</h3>
        <p>Pour les joueurs évoluant en catégorie sénior vous devez vous rendre au siège de l’ASFAC avant la fin juin pour procéder à une demande de démission à l’attention de votre ancien club. Afin de simplifier les démarches administratives 1 photo d’identité sera nécessaire pour que la demande de licence soit faite dès votre première visite.</p>
        <h3>Nouveau joueur :</h3>
        <p>Si vous ou votre enfant n’étiez licencié dans aucun club lors de la saison précédente il vous suffit de venir au secrétariat du club muni de 1 photo et d’une pièce d’identité ou le livret de famille.</p>
        <p>A la suite de ces démarches il vous sera demandé une cotisation (cf. tableau)</p>
        <p>Si votre cas est plus complexe (hors des périodes de mutations, conflit avec votre ancien club, étranger…) notre secrétaire général, Mr CARUSO Benjamin joignable au 04.67.80.07.44, vous précisera les démarches à effectuer.</p>
        <p>Le soir du lundi au vendredi de 16h00 à 19h00.</p>
        <a href="index.php?controller=Contact">POUR TOUS RENSEIGNEMENTS N'HESITEZ PAS A NOUS CONTACTER</a>
    </article>
    <article class="desc">
        <h3>Les joueurs sont répartis en 17 catégories d'âge de la manière suivante :</h3>
        <ul>
            <li>U6 et U6F : nés en 2015 - dès 5 ans</li>
            <li>U7 et U7F : nés en 2014</li>
            <li>U8 et U8F : nés en 2013</li>
            <li>U9 et U9F : nés en 2012</li>
            <li>U10 et U10F : nés en 2011</li>
            <li>U11 et U11F : nés en 2010</li>
            <li>U12 et U12F : nés en 2009</li>
            <li>U13 et U13F : nés en 2008</li>
            <li>U14 et U14F : nés en 2007</li>
            <li>U15 et U15F : nés en 2006</li>
            <li>U16 et U16F : nés en 2005</li>
            <li>U17 et U17F : nés en 2004</li>
            <li>U18 et U18F : nés en 2003</li>
            <li>U19 et U19F : nés en 2002</li>
            <li>SENIOR et SENIOR F : nés entre 1986 et 2001(les joueurs et joueuses nés en 2000 : Catégorie U20 et U20F)</li>
            <li>Séniors vétérans : nés avant 1986 (uniquement les joueurs)</li>
        </ul>
        <p>Féminines idem tableau ci dessus.</p>
    </article>
</section>