<section id="page">
    <h2>liens utiles</h2>
    <article class="desc1">
        <h4>Actufoot34</h4>
        <p>Le site de l'actualité du foot amateur dans la région.</p>
        <a href="http://www.actufoot34.com">www.actufoot34.com</a>
    </article>
    <article class="desc1">
        <h4>Fédération Française de football</h4>
        <p>Vous trouverez sur le site officiel de la fédération toutes les informations sur les compétitions nationales et sur les équipes nationales. Vous pourrez aussi consulter la partie formation où l’on vous propose de nombreux outils pour progresser dans la formation des jeunes joueurs ainsi que des informations sur les diplômes d’entraineur.</p>
        <a href="http://www.fff.fr">www.fff.fr</a>
    </article>
    <article class="desc1">
        <h4>Frontignan Thau Handball</h4>
        <p>Site officiel de nos amis handballeurs frontignanais.</p>
        <a href="http://www.frontignanthb.fr">www.frontignanthb.fr</a>
    </article>
    <article class="desc1">
        <h4>Kid's paradise</h4>
        <p>Aire de jeu pour les plus jeunes de 1 à 13 ans, kid's paradise est le lieu rêvé de tous les enfants. Retrouvez toutes les informations pratiques sur leur site.</p>
        <a href="http://www.kidsparadise.fr">www.kidsparadise.fr</a>
    </article>
    <article class="desc1">
        <h4>Ligue de l'Occitanie</h4>
        <p>Site officiel de la ligue de l'Occitanie de football. Vous y trouverez les résultats, les classements, les informations pratiques, les décisions des commissions…</p>
        <a href="http://occitanie.fff.fr">occitanie.fff.fr</a>
    </article>
    <article class="desc1">
        <h4>Site de l'AS Futsal Balarucois</h4>
        <p>Voilà le site de nos voisins Balarucois qui participeront au prochain championnat de France de futsal.</p>
        <a href="http://as-futsalbalarucois.footeo.com/">as-futsalbalarucois.footeo.com/</a>
    </article>
</section>