<section id="connect">
     <h2><i class="fas fa-user"></i> Se connecter avec un compte utilisateur</h2>
     <form method="post" id="formRegistration">
          <fieldset>
               <legend><i class="fas fa-lock"></i> Informations d'authentification</legend>
               <ul>
                    <li>
                         <label for="email">E-mail : </label>
                         <input type="email" id="email" name="email" value="" required>
                    </li>
                    <li>
                         <label for="password">mot de passe :</label>
                         <input type="password" id="password" name="password" required>
                    </li>
               </ul>
          </fieldset>
          <button type="submit">Connexion</button>
          <a class="button-cancel" href="index.php">Annuler</a>
     </form>
</section>