<section id="page">
    <h2>Partenaires</h2>
    <article class="desc">
        <h3>Les partenaires Officiels</h3>
        <img src="img/asfac-LOGO-herault.jpg" alt="logo_de_l_herault">
        <p>Un club, des hommes, un avenir et des ambitions...et vous?</p>
        <p>Association sportive à destination de la pratique du football dans toutes les catégories. C'est aussi une éducation, morale et sportive. Une volonté d'inculquer aux jeunes membres un ensemble de savoir être afin de développer chez eux, les valeurs essentielles du citoyen sportif: esprit de camaraderie, cohésion, notion du groupe et des force, politesse, respect des arbitres...</p>
        <p>L'asfac , c'est qui?Un président et son comité directeur, des commissions agissant dans divers domaines, la technique, les jeunes, la discipline et les animations. Un ensemble de 400 à 500 personnes unies par la passion du football et l'Amour du maillot.</p>
        <p>Ce sont aussi des éducateurs et des dirigeants. Les 4/5 des entraineurs sont des brevetés, une caractéristique qui place l'asfac dans le peloton des clubs régionaux. A noter que chaque année, ce sont quarante débutants qui rejoignent l'école de football du club.</p>
        <p>Que souhaite l'asfac?Bien plus que la vocation, l'obligation d'un club amateur est de former ses propres joueurs. Le football moderne, la lutte sans merci livrée lors des championnats et les surenchères incessantes des joueurs issus de centres de formation, imposent au sein du club du calibre de l'ASFAC, une politique saine et une volonté de former.</p>
        <p>En confiance réciproque avec son principal partenaire: la ville de Frontignan, l'ASFAC souhaite devenir une exemple régional avant de se hisser un peu plus haut dans sa hierarchie.</p>
    </article>
</section>