<section id="page">
   <h2>Le Stade</h2>
   <article class="desc">
      <img src="img/frontignan-le-stade.jpg" alt="stade-de-frontignan">
      <p>La pelouse du complexe Lucien Jean fut inaugurée en 1984 en la présence de l’actuel sélectionneur de l’équipe de France M. Domenech ainsi que de M. Lacombe aujourd’hui conseiller du M. Aulas.</p>
      <p>Avant cette date les équipes de l’ASFAC jouaient sur un terrain stabilisé édifié dont la construction avait débuté sous le mandat de M. Galabert, maire de Frontignan dans les années 1930.</p>
      <p>Ce terrain était marqué dans le sens Nord-Sud, à l’inverse du terrain actuel, c'est-à-dire de l’étang vers la voie ferrée.</p>
      <p>Pour le confort des spectateurs en même temps que la mise en place de la pelouse, fut érigée une tribune pouvant accueillir 500 personnes. Cette tribune sera couverte en 1995 afin de protéger les supporters.</p>
      <p>Ces supporters qui ont fait preuve à de maintes reprises d’une grande ferveur pour le club de leur cœur faisant ainsi honneur à la légende des ventres bleus. Le complexe de notre club est également composé d’un second terrain gazonné ainsi que de deux terrains synthétiques. Un sera dédié aux matchs et aux entrainements et un second sera réservé exclusivement aux entrainements. Ces nouvelles installations ont étée livrées à l’orée de la saison 2009.</p>
      <p>En plus de ces nouveaux terrains la mairie à mis à la disposition de l’ASFAC un nouveau bâtiment qui comprend le club house et la buvette. Ces installations se trouvent aux abords de l'entrée.</p>
   </article>
</section>
<section class="location">
   <h3>Nous trouver</h3>
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2896.927823681497!2d3.7576461157725705!3d43.441223374129464!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12b6b540a0fbf9c9%3A0xda6b54f197bb5575!2sParking%20du%20Stade%20Lucien%20Jean!5e0!3m2!1sfr!2sfr!4v1595412574263!5m2!1sfr!2sfr" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</section>