<section id="page">
    <h2>Le Staff</h2>
    <article class="desc">
        <h3>Le mot du conseil d’administration de l’ASFAC</h3>
        <p>L’objectif de ce site web est de promouvoir l’image de l’ ASFAC afin d’associer nos partenaires publics et privés au développement de la politique sportive que nous mettons en œuvre au quotidien.</p>
        <p>C'est aujourd’hui chose faite avec ce dernier maillon de la chaîne du partenariat qui nous lie à toutes ces entreprises et ces collectivités car sans elles nous ne pourrions pas avoir notre place sur l’échiquier régional.</p>
        <p>Bien sur, la vie d’un club ne se résume pas qu’à son aspect financier et le pendant indissociable de celui- ci est l’engagement de ces femmes et de ces hommes qui s’investissent au quotidien par leurs actions bénévoles et leur attachement indéfectible au club des ventres bleus.</p>
        <p>Outre le fait que ce site permettra à notre club d’exister et d’être connu et reconnu, il vous donnera la possibilité de le découvrir plus en détail et de participer à sa vie.</p>
        <p>A vous les acteurs du passé qui avez crée l’histoire de l’ASFAC</p>
        <p>A nous les gens du présent qui sommes garants de la bonne marche du club,</p>
        <p>A vous les prochaines générations d’en écrire l’avenir !</p>
        <p>Vive le football, vive l'ASFAC</p>
        <p>Sportivement</p>
    </article>
    <article class="desc">
        <h3>La commission des jeunes</h3>
        <img class="cache" src="img/asfac-organisation.jpg" alt="organisation de l'asfac">
        <p>La commission des jeunes, créée il y a plus de 12 ans, se compose essentiellement de bénévoles réunis autour d'une même passion.</p>
        <p>Le but premier de cette commissions est tout d'abord d'initier puis de former à la pratique du football, les jeunes des catégories "débutants" à la catégorie "- 15 ans".</p>
        <p>Elle est constituée d'un bureau (président, secrétaire, trésorier, intendant et cinq membres actifs) pour la gestion de l'administratif, et bien sûr d'une équipe sportive dirigée par un responsable technique encadré d'une quinzaine d'éducateurs, tous diplômés et d'une vingtaine de dirigeants. Cette équipe sportive encadre un effectif de joueurs de plus de 300 licenciés sur les plus de 400 que compte le club...</p>
        <p>C'est également la commission qui gère la préparation et l'organisation des manifestations sportives qui se déroulent tout au long d'une saison, entre autre le rassemblement débutant du mois de mai réunissant plus de 70 équipes.</p>
        <p>Bien évidemment, la formation de ces jeunes est un travail qui porte ses fruits au bout de plusieurs années, avec une réussite incertaine. Mais la plus grande satisfaction de cette commission est de voir progresser et évoluer dans les catégories "- 18 ans" et séniors, des joueurs formés au club depuis leur plus jeune âge. De même, nous sommes tout autant récompensés lorsqu'un joueur ayant fait ses classes dans nos équipes, nous quitte pour évoluer à un niveau supérieur.</p>
        <p>Au final, l'espoir de cette commission est qu'une partie de ces jeunes s'investissent à leur tour dans la même optique et soit le relais de ces bénévoles qui sont le moteur des clubs amateurs.</p>
        <p>Le président de la commission des jeunes : Thierry Frountil</p>
    </article>
</section>