<section id="page">
    <h2>Entrainements</h2>
    <article class="desc1">
        <h3>Planning et horaires 2020-2021</h3>
        <h4>SENIORS 1 :</h4>
        <p>Mardi - 19h15 à 21h00 ; Mercredi ; Vendredi - 19h00 à 21h00</p>
        <h4>SENIORS 2 :</h4>
        <p>Mardi ; Mercredi - 19h15 à 21h00 ; Vendredi - 19h00 à 20h45</p>
        <h4>FEMININES SENIORS :</h4>
        <p>Mardi ; Jeudi - 20h à 22h</p>
        <h4>GARDIENS U8/ U9/U10/U11/U12 :</h4>
        <p>Mercredi - 14h00 à 19h00</p>
        <h4>GARDIENS U15 :</h4>
        <p>Jeudi - 17h00 à 18h00</p>
        <h4>GARDIENS U17, U19 :</h4>
        <p>Mardi - 18h00 à 19h00</p>
        <h4>GARDIENS SENIORS :</h4>
        <p>Mardi - 19h00 à 21h00</p>
        <h4>VETERANS 1 :</h4>
        <p>Mercredi - 19h15 à 21h00</p>
        <h4>VETERANS 2 :</h4>
        <p>Lundi - 19h00 à 21h00</p>
        <h4>U19 :</h4>
        <p>Lundi - 19h15 à 21h00 ; Jeudi 19h00 - 21h00 ; Vendredi - 19h00 à 20h45</p>
        <h4>U17 1 :</h4>
        <p>Lundi ; Mardi ; Jeudi - 19h15 à 21h00</p>
        <h4>U17 2 :</h4>
        <p>Mercredi - 17h15 à 19h15 ; Vendredi - 17h30 à 19h30</p>
        <h4>U15 1 et 2 :</h4>
        <p>Lundi - 18h15 à 20h15 ; Mercredi - 17h30 à 19h15 ; Jeudi - 17h45 à19h15</p>
        <h4>FEMININES U13/U16</h4>
        <p>Mardi - 17h45 à 19h15 ; Vendredi - 18h00 à 20h00</p>
        <h4>U12 et 13 :</h4>
        <p>Mardi - 18h00 à 21h00 ; Mercredi -17h45 à 19h15 ; Vendredi - 17h45 à 19h00</p>
        <h4>U 10 / U11,1 et 2 :</h4>
        <p>Lundi - 17h45 à 19h15 ; Mercredi - 14h00 à 16h00</p>
        <h4>U10.1 et U10.2 :</h4>
        <p>Lundi - 18h00 à 19h00 ; Mercredi - 14h00 à 16h00</p>
        <h4>U9 :</h4>
        <p>Lundi - 17h45 à 19h15 ; Mercredi - 14h00 à 16h00</p>
        <h4>U8 :</h4>
        <p>Mercredi - 17h00 à19h00</p>
        <h4>U6, U7, FEMININES :</h4>
        <p>Mercredi - 14h00 à15h45</p>
    </article>
</section>